
github: [zgcCoding]
#issuehunt: USERNAME
#ko_fi: USERNAME
#liberapay: USERNAME
#open_collective: USERNAME
#patreon: USERNAME
#tidelift: PLATFORM-NAME/PACKAGE-NAME
#polar: USERNAME
#buy_me_a_coffee: USERNAME
#thanks_dev: u/gh/USERNAME
custom: ['https://zgccoding.github.io/support.html']
